services:
  - type: web
    name: bodywise-fitness-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://expo.dev,exp://,http://localhost:19000,http://localhost:19006
    healthCheckPath: /health 